package app.domain.models.enums;
public enum OperationType {
    ACCOUNT_OPENED,
    TRANSFER_CREATED, TRANSFER_EXECUTED, TRANSFER_REJECTED, TRANSFER_EXPIRED,
    LOAN_REQUESTED, LOAN_APPROVED, LOAN_REJECTED, LOAN_DISBURSED,
    DEPOSIT, WITHDRAWAL,
    USER_CREATED, USER_UPDATED, USER_DELETED
}
